2503ict-assign/2503ict-assign2/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::post('user/login', array('as' => 'user.login', 'uses' => 'UserController@login'));
Route::get('user/logout', array('as' => 'user.logout', 'uses' => 'UserController@logout'));
Route::get('user/search', array('as' => 'user.search', 'uses' => 'UserController@search'));

Route::resource('user', 'UserController');
Route::resource('post', 'PostController');
Route::resource('comment', 'CommentController');
Route::resource('friends', 'FriendController');


//-- Home page
Route::get('/', array('as'=>'home', 'uses'=> 'UserController@index'));


//-- View site documentation
Route::get('site_documentation', function()
{
	return View::make('doc/documentation');
});


/*
//-- Edit a post
Route::get('edit_post/{Id}', function($Id)
{
    $post = get_post($Id);
	return View::make('editPost')->withPost($post);
});

//-- View comments (Has errors)
Route::get('view_comments/{Id}', function($Id)
{
    $post = get_post($Id);
    $comments = get_comments($Id);
	
	if ($post) 
    {
        return View::make('viewComments')->withPost($post)->withComments($comments);
    } 
    else
    {
        die("Error viewing comments {no post}");
    }
});

//-- View site documentation
Route::get('site_documentation', function()
{
	return View::make('doc/documentation');
});


//-- Delete post
Route::get('del_post/{Id}', function($Id)
{   
    delete_post($Id);
	return Redirect::to(secure_url("/"));
});

//-- Delete comment
Route::get('del_comment/{Id}/{pId}', function($Id, $pId)
{   
    delete_comment($Id);
	return Redirect::back();
});

//-- Create post form 
Route::post('createPost', function()
{
    $name = Input::get('name');
    $title = Input::get('title');
    $message = Input::get('message');

    // If successfully created then display newly created item
    if ($name && $title && $message) 
    {
        $id = add_post($name, $title, $message);
        return Redirect::back();
    } 
    else
    {
        die("Error adding post");
    }
});

//-- Edit post form submitted
Route::post('editPostForm', function()
{
    $id = Input::get('id');
    $name = Input::get('name');
    $title = Input::get('title');
    $message = Input::get('message');
    
    if($name && $title && $message){
        update_post($id, $name, $title, $message);
    }
    
    $post = get_post($id);
    $comments = get_comments($id);
    // return Redirect::to( url("view_comments/$id") );
    return View::make('viewComments')->withPost($post)->withComments($comments);
});

//-- Comment form submitted
Route::post('createComment', function()
{
    $pId = Input::get('id');
    $name = Input::get('name');
    $message = Input::get('comment');
    $id = add_comment($pId, $name, $message);
    
    if ($id) 
    {
        // return Redirect::back();
        return Redirect::to("view_comments/$pId");
    } 
    else
    {
        die("Error adding comment");
    }
});





//-- Functions

//-- Gets all posts with a count of its comment
function get_posts_with_comments (){
    $sql = "SELECT Post.Id, Post.Title, Post.Message, Post.User_name, COUNT(Comment.Post_ID) as Comment_count
    FROM Post
    LEFT OUTER JOIN Comment 
    ON Post.Id = Comment.Post_ID
    GROUP BY Post.Id";
    
    $results = DB::select($sql);
    
    return $results;
}

//-- Gets all posts
function get_all_posts ()
{
    $sql = "select * from Post";
    $results = DB::select($sql);
    
    return $results;
}

//-- Get single post
function get_post($Id)
{
    $sql = "SELECT Post.Id, Post.Title, Post.Message, Post.User_name, COUNT(Comment.Post_ID) as Comment_count
    FROM Post
    LEFT OUTER JOIN Comment 
    ON Post.Id = Comment.Post_ID
    WHERE Post.Id = ?";
    
    $posts = DB::select($sql, array($Id));

	// If we get more than one post or none display an error
	if (count($posts) != 1) {
    die("Invalid query or result: $Id \n");
    }

    $post = $posts[0];
	return $post;
}

//-- Add post to database
function add_post($name, $title, $message) 
{
      $sql = "insert into Post (User_name, Title, Message) values (?, ?, ?)";
    
      DB::insert($sql, array($name, $title, $message));
    
      $id = DB::getPdo()->lastInsertId();
    
      return $id;
}

//-- Add comment to database
function add_comment ($pId, $name, $message)
{
    $sql = "insert into Comment (Message, User_name, Post_ID) values (?, ?, ?)";
    
    DB::insert($sql, array($message, $name, $pId));
    
    $id = DB::getPdo()->lastInsertId();
    
    return $id;
}

//-- Get all comments for a post 
function get_comments ($id)
{
    $sql = "select * from Comment where Post_ID = ?";
    $comments = DB::select ($sql, array($id));
    
    return $comments;
}

//-- Delete post
function delete_post($id)
{
    $sql1 = "delete from Comment where Post_ID = ?";
    DB::delete($sql1, array($id));
    
    $sql2 = "delete from Post where Id = ?";
    DB::delete($sql2, array($id));
}

//-- Delete comment
function delete_comment($id)
{
    $sql = "delete from Comment where Id = ?";
    DB::delete($sql, array($id));
}

//-- Edit/update a post
function update_post($id, $name, $title, $message)
{
    $sql = "update Post set Title = ?, Message = ? where id = ?";
    DB::update($sql, array($title, $message, $id));

    $post = get_post($id);
    return $post;
}
*/

2503ict-assign/2503ict-assign2/app/views/editPost.blade.php
@extends('layouts.master')


@section('title')
	Social Network - Edit Post
@stop


@section('content')
	<div class='row'>
    <!--Col 1-->
      <div class='col-xs-8'>
        <!--Edit Post form-->
        <div class="postForm">
          {{ Form::model( $post, array('method' => 'PUT', 'route' => array('post.update', $post->id )) ) }}
            {{ Form::label('title', 'Post Title: ') }}
            {{ Form::text('title') }}
            {{ $errors->first('title') }}
            <p></p>
            {{ Form::label('message', 'Message: ') }} 
            {{ Form::text('message') }}
            {{ $errors->first('message') }}
            <p></p>
            {{ Form::label('privacy', 'Privacy Setting:') }}
            {{ Form::select('privacy', array('private' => 'Private', 'public' => 'Public', 'friends' => 'Friends'), 'public'); }}
            <p></p>
            {{ Form::submit('Update') }} 
          {{ Form::close() }}
        </div>
        
      </div>
      
    <!--Col 2 ads-->
      <div class='col-xs-4'>
        <div class="adcontainer">
          <img class="adimg" src="{{asset('images/ads/heinz.jpg')}}"></img>
        </div>
        <div class="adcontainer">
          <img class="adimg" src="{{asset('images/ads/smoking.jpg')}}"></img>
        </div>
      </div>
      
    </div>
@stop

2503ict-assign/2503ict-assign2/app/views/editUser.blade.php
@extends('layouts.master')


@section('title')
	Social Network - Edit User Information
@stop


@section('content')
	<div class='row'>
    <!--Col 1-->
      <div class='col-xs-8'>
        <!--Edit user form-->
        <div class="postForm">
          {{ Form::model( $user, array('method' => 'PUT', 'route' => array('user.update', $user->id )) ) }}
            <!--{{ Form::hidden('email', $user->email) }}-->
            {{ Form::label('full_name', 'Name: ') }}
            {{ Form::text('full_name') }}
            {{ $errors->first('full_name') }}
            <p></p>
            {{ Form::label('date_of_birth', 'Date of birth: ') }} 
            {{ Form::text('date_of_birth') }}
            {{ $errors->first('date_of_birth') }}
            <p></p>
            {{ Form::label('image', 'Profile Image: ') }} 
            {{ Form::file('image') }}
            {{ $errors->first('image') }}
            <p></p>
            {{ Form::label('password', 'Password: ') }} 
            {{ Form::password('password') }}
            {{ $errors->first('password') }}
            <p></p>
            {{ Form::label('password_confirmation', 'Confirm Password: ') }} 
            {{ Form::password('password_confirmation') }}
            {{ $errors->first('password_confirmation') }}
            <p></p>
            {{ Form::label('email', 'Email Address: ') }} 
            {{ Form::email('email') }}
            {{ $errors->first('email') }}
            <P></P>
            {{ Form::submit('Update') }} 
          {{ Form::close() }}
        </div>
        
      </div>
      
    <!--Col 2 ads-->
      <div class='col-xs-4'>
        <div class="adcontainer">
          <img class="adimg" src="{{asset('images/ads/heinz.jpg')}}"></img>
        </div>
        <div class="adcontainer">
          <img class="adimg" src="{{asset('images/ads/smoking.jpg')}}"></img>
        </div>
      </div>
      
    </div>
@stop

2503ict-assign/2503ict-assign2/app/views/friends.blade.php
@extends('layouts.master')


@section('title')
	Social Network - Friends
@stop


@section('content')
	<div class='row'>
    <!--Col 1-->
      <div class='col-xs-8'>
        
        <!--User List-->
        <div class="commentTimeline">
          
          @if (count($friends) == 0)
          <p>No friends found!</p>
          
          @else 
          @foreach($friends as $friend)
            <div class="comment">
              {{-- */ $u = User::find($friend->friend_id); /* --}}
              <img class='photo' src="{{ asset($u->image->url('thumb')) }}">
              <b>Name:</b> {{{ $u->full_name }}} <br> 
              {{ link_to_route('user.show', 'View Profile', array( $u->id )) }}
            </div>
          @endforeach
          @endif
        </div>
        
      </div>
      
    <!--Col 2 ads-->
      <div class='col-xs-4'>
        <div class="adcontainer">
          <img class="adimg" src="{{asset('images/ads/heinz.jpg')}}"></img>
        </div>
        <div class="adcontainer">
          <img class="adimg" src="{{asset('images/ads/smoking.jpg')}}"></img>
        </div>
      </div>
      
    </div>
@stop

2503ict-assign/2503ict-assign2/app/views/home.blade.php
@extends('layouts.master')


@section('title')
	Social Network - Home
@stop


@section('content')
	<div class='row'>
    <!--Col 1-->
      <div class='col-xs-3'>
        
        <!--Login form-->
        <div class="postForm">
          <h3>Login</h3><br>
          @if (Auth::check())
            {{ Redirect::route('user.show', Auth::user()->id) }}
          @else
            {{ Form::open( array('url' => secure_url('user/login')) ) }}
              {{ Form::label('email', 'Email Address: ') }}
              {{ Form::email('email') }}
              {{ $errors->first('email') }}
              <p></p>
              {{ Form::label('password', 'Password: ') }} 
              {{ Form::password('password') }}
              {{ $errors->first('password') }}
              <p></p>
              {{ Form::submit('Login') }} 
            {{ Form::close() }}
          @endif
        </div>

      </div>

      
    <!--Col 2 register form-->
      <div class='col-xs-5'>
        
        <!--Registration form-->
        <div class="postForm">
          <h3>Sign up</h3><br>
          {{ Form::open( array('url' => secure_url('user'), 'files'=> true ) ) }}
            {{ Form::label('full_name', 'Full Name: ') }} 
            {{ Form::text('full_name') }}
            {{ $errors->first('full_name') }}
            <p></p>
            {{ Form::label('date_of_birth', 'Date Of Birth: ') }} 
            {{ Form::text('date_of_birth') }}
            {{ $errors->first('date_of_birth') }}
            <p></p>
            {{ Form::label('image', 'Profile Image: ') }} 
            {{ Form::file('image') }}
            {{ $errors->first('image') }}
            <p></p>
            {{ Form::label('email', 'Email Address: ') }} 
            {{ Form::email('email', 'example@gmail.com') }}
            {{ $errors->first('email') }}
            <p></p>
            {{ Form::label('password', 'Password: ') }} 
            {{ Form::password('password') }}
            {{ $errors->first('password') }}
            <p></p>
            {{ Form::label('password_confirmation', 'Confirm Password: ') }} 
            {{ Form::password('password_confirmation') }}
            {{ $errors->first('password_confirmation') }}
            <p></p>
            {{ Form::submit('Sign up') }} 
          {{ Form::close() }}
        </div>
        
      </div>
      
      
      <!--Col 3 ads-->
      <div class='col-xs-4'>
        <div class="adcontainer">
          <img class="adimg" src="{{asset('images/ads/heinz.jpg')}}"></img>
        </div>
        <div class="adcontainer">
          <img class="adimg" src="{{asset('/images/ads/smoking.jpg')}}"></img>
        </div>
      </div>
      
  </div>
@stop

2503ict-assign/2503ict-assign2/app/views/profile.blade.php
@extends('layouts.master')


@section('title')
	Social Network - Profile
@stop


@section('content')
	<div class='row'>
      <!--Col 1-->
      <div class='col-xs-8'>
        
        <!--User information-->
        <div class = "postForm">
          <h4> {{{ $user->full_name}}}'s information</h4>
          <img class='photo' src="{{ asset($user->image->url('thumb')) }}">
          
          <b>Name:</b> {{{ $user->full_name }}} <br> 
          <b>Age:</b> 
          {{-- */
              $oDateNow = new DateTime();
              $oDateBirth = new DateTime($user->date_of_birth);
              $oDateIntervall = $oDateNow->diff($oDateBirth); 
              echo $oDateIntervall->y;
          /* --}}
          <br>
          <b>Date Joined: </b> {{{ $user->created_at }}} <br> 
          {{ link_to_route('friends.show', 'View friends', array($user->id)) }}
          <p></p>
          
          <!--Check the profile user and logged in users relationship-->
          @if (Auth::check() && $user->id == Auth::user()->id)
            {{ link_to_route('user.edit', 'Edit Profile Information', array( $user->id )) }} 
          @elseif (Auth::check())
            {{-- */ $authUser = User::find(Auth::user()->id); 
                    $friends = $authUser->friend;
                    $truefalse = false;
                    foreach ($friends as $friend){
                      if($friend->friend_id == $user->id){
                        $truefalse = true;
                        $friendId = $friend->id;
                      }
                    }
            /* --}}
            @if ( $truefalse )
              {{ Form::open(array('method' => 'DELETE', 'route' => array('friends.destroy', $friendId))) }}
              {{ Form::hidden('user_id', Auth::user()->id) }} 
              {{ Form::hidden('friend_id', $user->id) }}
              {{ Form::submit('Remove Freind', array('class' => 'btn btn-primary')) }} 
              {{ Form::close() }}
            @else
              {{ Form::open( array( 'action' => 'FriendController@store') ) }}
              {{ Form::hidden('user_id', Auth::user()->id) }} 
              {{ Form::hidden('friend_id', $user->id) }}
              {{ Form::submit('Add Freind', array('class' => 'btn btn-primary')) }} 
              {{ Form::close() }}
            @endif
          @endif
        </div>
        
        <!--Post form-->
        <div class='postForm'>
          @if (Auth::check() && Auth::user()->id == $user->id)
            {{ Form::open(array('action' => 'PostController@store')) }}
              
              {{ Form::hidden('user_id', $user->id) }}
              
              {{ Form::label('title', 'Post Title: ') }}
              {{ Form::text('title') }}
              {{ $errors->first('title') }}
              <p></p>
              {{ Form::label('message', 'Message: ') }} 
              {{ Form::text('message') }}
              {{ $errors->first('message') }}
              <p></p>
              {{ Form::label('privacy', 'Privacy Setting:') }}
              {{ Form::select('privacy', array('private' => 'Private', 'public' => 'Public', 'friends' => 'Friends'), 'public'); }}
              <p></p>
              {{ Form::submit('Post') }} 
            {{ Form::close() }}
          @else
          <h4>Post Timeline </h4>
          @endif
        </div>
        
        
        <!--Post timeline-->
        <div class="postTimeline">
          
          @if (count($posts) == 0)
          <p>No posts!</p>
          
          @else 
          @foreach( $posts as $post)
            {{-- */ $ok = 'false'; /* --}}
            @if ($post->privacy == 'public')
                {{-- */ $ok = 'true' /* --}}
            @elseif ($post->privacy == 'private' && Auth::check() && Auth::user()->id == $user->id)
                {{-- */ $ok = 'true' /* --}}
            @elseif ($post->privacy == 'friends' && Auth::check() && $truefalse)
                 {{-- */ $ok = 'true' /* --}}
            @endif
            
            @if ($ok == 'true')
              <div class="post">
                <img class='photo' src="{{ asset($user->image->url('thumb')) }}">
                <b>Title:</b> {{{ $post->title }}} <br> 
                <b>Message:</b> {{{ $post->message }}} <br>
                <b>Privacy:</b> {{{ $post->privacy }}} <br>
                <b>Created:</b> {{{ $post->created_at }}} <br>
                {{ link_to_route('post.show', 'View Comments', array( $post->id )) }} <br>
                @if (Auth::check() && $user->id == Auth::user()->id)
                  {{ link_to_route('post.edit', 'Edit', array( $post->id )) }} 
                  <p></p>
                  {{ Form::open(array('method' => 'DELETE', 'route' => array('post.destroy', $post->id))) }}
                  {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }} 
                  {{ Form::close() }}
                @endif
              </div>
            @endif
          @endforeach

          @endif
        </div>
      </div>
      
      
      <!--Col 2 ads-->
      <div class='col-xs-4'>
        <div class="adcontainer">
          <img class="adimg" src="{{asset('images/ads/heinz.jpg')}}"></img>
        </div>
        <div class="adcontainer">
          <img class="adimg" src="{{asset('images/ads/smoking.jpg')}}"></img>
        </div>
      </div>
      
    </div>
@stop

2503ict-assign/2503ict-assign2/app/views/search.blade.php
@extends('layouts.master')


@section('title')
	Social Network - Search
@stop


@section('content')
	<div class='row'>
    <!--Col 1-->
      <div class='col-xs-8'>
        
        <!--User List-->
        <div class="commentTimeline">
          
          @if (count($users) == 0)
          <p>No users found!</p>
          
          @else 
          @foreach($users as $user)
            <div class="comment">
              {{-- */ $u = User::find($user->id); /* --}}
              <img class='photo' src="{{ asset($u->image->url('thumb')) }}">
              <b>Name:</b> {{{ $u->full_name }}} <br> 
              {{ link_to_route('user.show', 'View Profile', array( $u->id )) }}
            </div>
          @endforeach
          @endif
        </div>
        
      </div>
      
    <!--Col 2 ads-->
      <div class='col-xs-4'>
        <div class="adcontainer">
          <img class="adimg" src="{{asset('images/ads/heinz.jpg')}}"></img>
        </div>
        <div class="adcontainer">
          <img class="adimg" src="{{asset('images/ads/smoking.jpg')}}"></img>
        </div>
      </div>
      
    </div>
@stop

2503ict-assign/2503ict-assign2/app/views/viewPost.blade.php
@extends('layouts.master')


@section('title')
	Social Network - Comments
@stop


@section('content')
	<div class='row'>
    <!--Col 1-->
      <div class='col-xs-8'>
        <!--Post-->
        <div class="comPost">
          {{-- */ $u = User::find($post->user_id) /* --}}
          <img class='photo' src="{{ asset($u->image->url('thumb')) }}">
          <!--<b>Name:</b> {{{ $post->User_name }}} <br> -->
          <b>Title:</b> {{{ $post->title }}} <br> 
          <b>Message:</b> {{{ $post->message }}} <br>
          <b>Privacy:</b> {{{ $post->privacy }}} <br>
          <!--<b>Number of comments:</b> {{{ $post->Comment_count }}}<br>-->
        </div>
        
        <!--Comment form-->
        @if (Auth::check())
          <div class='commentForm'>
            {{ Form::open(array('action' => 'CommentController@store')) }} 
          
            {{ Form::hidden('post_id', $post->id) }} 
            {{ Form::hidden('user_id', Auth::user()->id) }} 
            {{ Form::label('message', 'Message: ') }} 
            {{ Form::text('message') }}
            {{ $errors->first('message') }}
            <p></p>
            {{ Form::submit('Comment') }} 
            {{ Form::close() }}
          </div>
        @endif
        
        <!--Comment timeline-->
        <div class="commentTimeline">
          
          @if (count($comments) == 0)
          <p>You have no Comments!</p>
          
          @else 
          <h4 class="comment">Comments</h4>
          @foreach($comments as $comment)
            <div class="comment">
              {{-- */ $u = User::find($comment->user_id) /* --}}
              <img class='photo' src="{{ asset($u->image->url('thumb')) }}">
              <b>{{{ User::find($comment->user_id)->full_name }}}</b> <br> 
              <b>Message:</b> {{{ $comment->message }}} <br>
              <b>Created:</b> {{{ $comment->created_at }}} <br>
              @if (Auth::check() && $comment->user_id == Auth::user()->id)
                <p></p>
                {{ Form::open(array('method' => 'DELETE', 'route' => array('comment.destroy', $comment->id))) }}
                {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }} 
                {{ Form::close() }}
              @endif
            </div>
          @endforeach
          @endif
        </div>
        {{ $comments->links() }}
        
      </div>
      
      
    <!--Col 2 ads-->
      <div class='col-xs-4'>
        <div class="adcontainer">
          <img class="adimg" src="{{asset('images/ads/heinz.jpg')}}"></img>
        </div>
        <div class="adcontainer">
          <img class="adimg" src="{{asset('images/ads/smoking.jpg')}}"></img>
        </div>
      </div>
      
    </div>
@stop